language: node_js
node_js:
  - 'node'
  - '6'
  - '4'
addons:
  code_climate:
    repo_token: c78cf71f87560d21b8e34dcec80a513b6b0dd5435bb7d9ea9d7ca3aa2be289b2
notifications:
  email: false
  slack:
    rooms:
      secure: OSb2xYOlrY1rV79UVCThssOTUGWAyTHGKAuZMfoLuF2j/Pb7urxQsum8KTYpKGoHi2C07y4UGnYN7UQ1LeEv1AS91fVpq+prDTGWOQLxVkfN0wSkHYZXp8X8E72xyLpU/5cke85WYxNR1QzsUYETuxgU5ScrupNjK6TWdW7PLZ5bIEty7jDWU9NLLZoRkL2FYE5EnxYlsnxK3B02dwWsZVd8oFlsiGvgV2RuQu74eVoLGV1xUaKggfzkmatTA9cfMl+PAPZiqxfaVA2PrYn/CfTy83ATz0PF9xlUf73Vg+CT1iaTszUfG7qr3uNTZ7x9XCu4RQ6ctXfRp54tAw4Ya3zh+EEKd/g2c68ZsaICTx4UHsqpl19jZO55KCEsjY9VoP7+XhfkB3YswGXnwoTHUWuMXmCZXfsGGvuztpiY7ljYJ/JqkCf2OEy0H5msvxhiiwfS0UXGYL2GIesESXqVzI1sGtR73BzI02gS965umd4gCZfVMzj2EltjKKLigGIMU5kA7ITzdfIK7csqnsuRX7y4gGpDahFXqs763LPTbiWcbjwn2je7YStL24KdECw3Dsu9VhIB1zQePhzdTfnnZaJoRC2vomvHlCfdNbSIg4pLd1vLAqjpn0mFkrJUywinC2qKlfyNUO2R8V0kd0oLf97qqzEWIi74yPWAowqkavM=
before_script:
  - npm install -g codeclimate-test-reporter
after_script:
  - codeclimate-test-reporter < coverage/lcov.info
sudo: false
