language: node_js
node_js:
- node
- '6'
- '4'
addons:
  code_climate:
    repo_token: 7e55a60fe202e7447108777e8b70bee8f74909d00ef6ec4dfea001b62f06b22f
notifications:
  email: false
  slack:
    rooms:
      secure: jWPX08BteyyydO9Pvv9T6jVikRBGEl5BWy3a/N6I/t8u9haxqjgCEnDRbauoXz/o0bkHFckoofVPsRmIE/l40J82gJOna+wi5dS9/sPhzv+6pw52roKL7+0gCW9Wdpp7rBBkgkZIfycpEHP8Xoi2dg7/uiVYgovJvYxVv5Ng/LvQ1iHIGrIaLn6uj9uakbfCYUFWRhIffqSu0JH1vTJRH1vbKIgamFOEDGTdaFbmGfiJ3RRR1E/6Um8Nd/NI7IOM1kNZ2CMqtiHr2v7B5iCVFix2uyas73BxN4sz5Vcl1BC/CfTxqrS9gK/AK1d71G6y/n7NNN4xA+c40yvsusxm3HfV0ifkMK1/8txXKdu79E4RF6hXukCLxnjYnH1VAix9ivHpfs6IqWMrkidQx7c9wrprKAPP0uOzlWTZCHVnVXGw2fewKgLxhO4OwllcvgBRasxeLYPOYSz+PX0HnwE1rGYho3o9Muby89P7Y6GQTMAYiHpGetGxbY5SWL2iwvofw0AxKxqxv1Z89sMDgQkNUVwsskPpnG9a5Uqr8Yi2sH3RB3WU8UmYnANKKHPyOiDTyTYiXGr9O2UdQoFYSSvY8W9usrdLB5ozaJ7YXdkhhLZTH22iy9HqbJC6oakDN9zO5/2eqM/6wlxoShPE8WBsayaG9VNHG5djknwchW/1i6A=
before_script:
- npm install -g codeclimate-test-reporter
after_script:
- codeclimate-test-reporter < coverage/lcov.info
sudo: false
